### ISSUE TITLE
Needs a makefile

### ISSUE THREAD

**Issue by ChrisCoxArt** [intel/cppnnml#16]
The project needs a makefile to simplify building and testing (once you get it to build again).

**Comment by dmcleran** [comment]
There is a wiki (https://github.com/intel/cppnnml/wiki) with detailed directions for how to compile each example. Makefile is not a bad idea but most of the examples are 1-liners with respect to compiling.

**Comment by ChrisCoxArt** [comment]
Your code relies on hidden switches/defines to make your code compile, which are documented in a wiki that doesn't download with the code repo. You NEED a makefile.  You NEED better documentation. And it sounds like you need some serious architectural review.

**Comment by dmcleran** [comment]
Makefile added for the xor example.

**Comment by dmcleran** [comment]
Makefiles added for all examples as well as the unit tests.
